apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: opa 
  namespace: default 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: opa 
  template: 
    metadata: 
      labels: 
        app: opa 