apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: opa 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: opa 
  template: 
    metadata: 
      labels: 
        app: opa 
    spec: 
      containers: 
      - name: opa 
        image: openpolicyagent/opa 
        ports: 
        - containerPort: 8181 
        resources: 
          requests: 
            memory: "64Mi" 
            cpu: "100m" 
          limits: 
            memory: "128Mi" 
            cpu: "200m" 
        command: 
        - "run" 
        - "--server" 