apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: opa-policy 
data: 
  policy.rego: | 
    package opa.kubernetes 

    deny[msg] { 
      input.review.object.kind == "ConfigMap" 
      input.review.object.data.confidential_data 
      msg = "Encryption is required for confidential data." 
    } 