global: 
  enabled: true 
  imageRegistry: docker.io 
  imagePullSecrets: 
    - name: my-registry-secret 
server: 
  enabled: true 
  image: 
    repository: vault 
    tag: 1.8.4 
    pullPolicy: IfNotPresent 
  env: 
    VAULT_DEV_ROOT_TOKEN_ID: "myroot" 
    VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200" 
    VAULT_ADDR: "http://127.0.0.1:8200" 
  extraVolumes: 
    - type: secret 
      name: vault-tls-cert 
  extraVolumeMounts: 
    - name: vault-tls-cert 
      mountPath: /vault/tls 
      readOnly: true 
  ingress: 
    enabled: true 
    apiVersion: networking.k8s.io/v1 
    pathType: Prefix 
    hosts: 
      - vault.local 
    paths: 
      - path: "/" 
        pathType: Prefix 
        backend: 
          serviceName: vault 
          servicePort: 8200 
    tls: 
      - secretName: vault-tls-cert 
        hosts: 
          - vault.example.com # Enter your host name here
ui: 
  enabled: true 
  serviceType: ClusterIP 
replicaCount: 1 
persistence: 
  enabled: true 
  size: 10Gi 
  storageClass: standard 