--- 

elasticsearchHosts: "http://10.116.200.220:9200" 
replicas: 1 
image: "docker.elastic.co/kibana/kibana" 
imageTag: "7.13.0" 
imagePullPolicy: "IfNotPresent" 
resources: 
  requests: 
    cpu: "1000m" 
    memory: "1Gi" 
  limits: 
    cpu: "1000m" 
    memory: "1Gi" 

healthCheckPath: "/api/status" 
httpPort: 5601 
service: 
  type: LoadBalancer #ClusterIP 
  loadBalancerIP: "" 
  port: 5601 
  nodePort: "" 
  labels: {} 
  annotations: {} 
    # cloud.google.com/load-balancer-type: "Internal" 
    # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0 
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true" 
    # service.beta.kubernetes.io/openstack-internal-load-balancer: "true" 
    # service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true" 
  loadBalancerSourceRanges: [] 
    # 0.0.0.0/0 
  httpPortName: http 